# nixpacks.toml

[phases.setup]
nixPkgs = [
    "glib",
    "nss",
    "nspr",
    "atk",
    "libdrm",
    "libxkbcommon",
    "mesa",
    "alsa-lib",
    "pango",
    "cairo",
    "playwright-driver"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/tmp/ms-playwright"
PYTHONUTF8 = "1"
PYTHONIOENCODING = "utf-8"
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
